# -*- coding: utf-8 -*-
"""pro-c135-reference-code.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/shubhamwhj/a22a6f22846391da4e3192b3aab39819/pro-c135-reference-code.ipynb

## Exploring Solar Systems with Statistics

In today's class, we will plot a few graphs and apply statistics to the data we have! We will also try to find some interesting insights about different solar systems.

\
Before we do that, let us recall the fields that are left in the CSV -

*   ***name*** - name of the planet
*   ***light_years_from_earth*** - Distance of the exo-planet from earth in light years
*   ***planet_mass*** - Mass of the planet
*   ***stellar_magnitude*** - This is the brightness of the host star of the planet when observed from Earth (just as the sun is our host star)
*   ***discovery_date*** - This is the year of discovery for the exo-planet
*   ***planet_type*** - This is the type of the planet (Gas Giant, Super Earth, etc.)
*   ***planet_radius*** - This is the radius of the exo-planet with respect to Earth or Jupiter.
*   ***orbital_radius*** - This is the average distance of this exo-planet from its sun. Just like our solar system has 1 sun, there are multiple solar systems that contain many planets and sun(s)
*   ***orbital_period*** - This is the time it takes to complete one orbit of it’s sun
*   ***eccentricity*** - This denotes how circular the orbit is. It might be oval in shape too. The lower the eccentricity, the more circular is the orbit
*   ***solar_system_name*** - The name of the host solar system
*   ***planet_discovery_method*** - This is the discovery method which was used to find this exo-planet
*   ***planet_orbital_inclination*** - This is the orbital inclination, which means that it is the tilt of the exo-planet’s orbit when it revolves around its sun
*   ***planet_density*** - This is the density of the planet
*   ***right_ascension*** - This is the right ascension of the planetary system, which is the east-west coordinate by which the position of this planet is measured
*   ***declination*** - This is the north-south coordinate by which the position of the planet is measured
*   ***host_temperature*** - This is the temperature of the host star in Kelvin
*   ***host_mass*** - This is the amount of mass contained in the host star
*   ***host_radius*** - This is the radius of the host star

\
Great! Now since we already know that we have 8 planets in our solar system, let's see if we can find out if there are any similar solar systems like us in the universe by seeing how many planets are there in the other solar systems.


For this, we have a column known as ***solar_system_name*** in our CSV. Using this, we can create a dictionary to maintain the count of planets each solar system has!

Before we write any code for this, let's just upload the CSV to our Colab first!
"""

!git clone https://github.com/procodingclass/PRO-NASA-Exoplanet-Processed-Data.git

"""Now let's just write the code to read the CSV"""

import csv

rows = []

with open("/content/PRO-NASA-Exoplanet-Processed-Data/main.csv", "r") as f:
  csvreader = csv.reader(f)
  for row in csvreader:
    rows.append(row)

headers = rows[0]
planet_data_rows = rows[1:]
print(headers)
print(planet_data_rows[0])

"""Now let's find the number of planets in each of the solar system!"""

solar_system_planet_count = {}

for planet_data in planet_data_rows:
  if solar_system_planet_count.get(planet_data[11]):
    solar_system_planet_count[planet_data[11]] += 1
  else:
    solar_system_planet_count[planet_data[11]] = 1

print(solar_system_planet_count)

max_solar_system = max(solar_system_planet_count, key=solar_system_planet_count.get)

print("Solar system NAME with maximum planets: ", max_solar_system)
print("Number of planets: ", solar_system_planet_count[max_solar_system])

"""##Our Next Planet Home?

Solar system **KOI-351** has **8** planets!

Could this be our next home?

Let's create a list of all the planets in this solar system so we can take a deeper look at it!
"""

temp_planet_data_rows = list(planet_data_rows)

for planet_data in temp_planet_data_rows:

  planet_mass = planet_data[3]

  if planet_mass.lower() == "unknown":
    planet_data_rows.remove(planet_data)
    continue
  else:
    planet_mass_value = planet_mass.split(" ")[0]
    planet_mass_ref = planet_mass.split(" ")[1]
    if planet_mass_ref == "Jupiters":
      planet_mass_value = float(planet_mass_value) * 317.8
    planet_data[3] = planet_mass_value

  planet_radius = planet_data[7]

  if planet_radius.lower() == "unknown":
    planet_data_rows.remove(planet_data)
    continue
  else:
    planet_radius_value = planet_radius.split(" ")[0]
    planet_radius_ref = planet_radius.split(" ")[2]
    if planet_radius_ref == "Jupiter":
      planet_radius_value = float(planet_radius_value) * 11.2
    planet_data[7] = planet_radius_value

print(len(planet_data_rows))

koi_351_planets = []

for planet_data in planet_data_rows:
  if max_solar_system == planet_data[11]:
    koi_351_planets.append(planet_data)

print(len(koi_351_planets))
print(koi_351_planets)

"""Great, now let's plot a bar chart on the planet_mass column with these 6 planet data -"""

import plotly.express as px

koi_351_planet_masses = []
koi_351_planet_names = []

for planet_data in koi_351_planets:
  koi_351_planet_masses.append(planet_data[3])
  koi_351_planet_names.append(planet_data[1])

koi_351_planet_masses.append(1)
koi_351_planet_names.append("Earth")

fig = px.bar(x=koi_351_planet_names, y=koi_351_planet_masses)
fig.show()

"""## Fun Fact

Now before we proceed, let's learn a fun fact -

The great scientist **Albert Einstein** derived a formula with which we can calculate the gravity of any planet.

The formula is this -


<img src='https://s3-whjr-curriculum-uploads.whjr.online/6019d9d9-5f2f-4b39-b752-32ac5a9bc046.png' width='150'>

Here,

* **G** is a **gravitational constant**, which means that it will always be the same.

* **m** is the **mass of Earth** (or any other planet if we are calculating it for another planet)

* **r** is the **radius of the planet**

Here, we can see an inverse relation between the the radius of the planet and the gravity.

<img src='https://s3-whjr-curriculum-uploads.whjr.online/b075ced0-0ac3-4432-af07-cec0a08cf190.png' width='150'>

**The more the radius (and bigger the planet), the lesser would be gravity.**

But then, we also see a direct relation between the mass of the planet and the gravity.

<img src='https://s3-whjr-curriculum-uploads.whjr.online/2351f2d9-eed5-491e-9646-612d762b13be.png' width='150'>

**The more the mass of the planet, the more will be the gravity.**

Our **Earth’s gravity is $9.8 m/s^2$**, and we as humans are accustomed to it. In order for us to exist on any other planet, the gravity should be close to what we have here.


**Mars** has a gravity of **$3.711 m/s^2$** and **Moon** has a gravity of **$1.62 m/s^2$**.

## Scatter plot

Given what we have just learnt, let’s try to plot a scatter plot for all the planets, where we will keep the mass of the planet as the Y-Coordinate, The Radius of the Planet as X-Coordinate, and the size of the blob as the gravity of it. Let’s see if we can find anything interesting!

The value of **G** (Gravitational Constant) is **6.674e-11***

**Mass of Earth = 5.972e+24**

**Radius of Earth = 6371000**

**Note** - Since we have the ***planet_mass*** and ***planet_radius*** with Reference to Earth, don’t forget to multiple the mass of the earth and the radius of the earth with these values!
"""

temp_planet_data_rows = list(planet_data_rows)

for planet_data in temp_planet_data_rows:
  if planet_data[1].lower() == "hd 100546 b":
    planet_data_rows.remove(planet_data)

planet_masses = []
planet_radiuses = []
planet_names = []

for planet_data in planet_data_rows:
  planet_masses.append(planet_data[3])
  planet_radiuses.append(planet_data[7])
  planet_names.append(planet_data[1])

planet_gravity = []

for index, name in enumerate(planet_names):
  gravity = (float(planet_masses[index])*5.972e+24) / (float(planet_radiuses[index])*float(planet_radiuses[index])*6371000*6371000) * 6.674e-11
  planet_gravity.append(gravity)

fig = px.scatter(x=planet_radiuses, y=planet_masses, size=planet_gravity, hover_data=[planet_names])
fig.show()

"""## Fun Fact

**Our standing human bodies can withstand a gravitational force 90 times stronger than earth!**

## Habitable Gravity Planets

Although that is going to be a bit extreme, we can still survive at 10 times the gravity we have at Earth.

Let’s list down all the names of the planets that have Gravity of 100 or less!
"""

low_gravity_planets = []
for index, gravity in enumerate(planet_gravity):
  if gravity < 100:
    low_gravity_planets.append(planet_data_rows[index])

print(len(low_gravity_planets))

"""Let's take a look at our headers again"""

print(headers)

"""Here, we have a header called planet_type. Let's see how many different types of planets are we dealing with -"""

planet_type_values = []
for planet_data in planet_data_rows:
  planet_type_values.append(planet_data[6])

print(list(set(planet_type_values)))

"""Now that we have the types of planets that are out there, let’s understand these terms -

**Neptune-like** => These planets are like neptune! They are big in size and have rings around them. They are also made of Ice.

**Super-Earth** => These are the planets that have mass greater than earth but smaller than that of Neptune! (Neptune is 17 times Earth)

**Terrestrial** => It is a planet that is composed primarily of silicate rocks or metals (Like Earth, Mars)

**Gas Giant** => There are the planets that are composed of Gas (Hydrogen and Helium)

Based on this, let’s try to do some clustering to see if there is any relation between planet type and mass of the planet. It looks like there is but let’s see.

"""

planet_masses = []
planet_radiuses = []

for planet_data in low_gravity_planets:
  planet_masses.append(planet_data[3])
  planet_radiuses.append(planet_data[7])

fig = px.scatter(x=planet_radiuses, y=planet_masses)
fig.show()

planet_types = []

for planet_data in low_gravity_planets:
  planet_types.append(planet_data[6])

fig = px.scatter(x=planet_radiuses, y=planet_masses, color=planet_types)
fig.show()

suitable_planets = []

for planet_data in low_gravity_planets:
  if planet_data[6].lower() == "terrestrial" or planet_data[6].lower() == "super earth":
    suitable_planets.append(planet_data)

print(len(suitable_planets))

print(headers)

temp_suitable_planets = list(suitable_planets)
for planet_data in temp_suitable_planets:
  if planet_data[8].lower() == "unknown":
    suitable_planets.remove(planet_data)

for planet_data in suitable_planets:
  if planet_data[9].split(" ")[1].lower() == "days":
    planet_data[9] = float(planet_data[9].split(" ")[0]) #Days
  else:
    planet_data[9] = float(planet_data[9].split(" ")[0])*365 #Years
  planet_data[8] = float(planet_data[8].split(" ")[0])

orbital_radiuses = []
orbital_periods = []
for planet_data in suitable_planets:
  orbital_radiuses.append(planet_data[8])
  orbital_periods.append(planet_data[9])

fig = px.scatter(x=orbital_radiuses, y=orbital_periods)
fig.show()

goldilock_planets = list(suitable_planets)          #We will leave suitable planet list as it is

temp_goldilock_planets = list(suitable_planets)
for planet_data in temp_goldilock_planets:
  if planet_data[8] < 0.38 or planet_data[8] > 2:
    goldilock_planets.remove(planet_data)

print(len(suitable_planets))
print(len(goldilock_planets))

planet_speeds = []
for planet_data in suitable_planets:
 distance = 2 * 3.14 * (planet_data[8] * 1.496e+9)
 time = planet_data[9] * 86400
 speed = distance / time
 planet_speeds.append(speed)


speed_supporting_planets = list(suitable_planets) #We will leave suitable planet list as it is


temp_speed_supporting_planets = list(suitable_planets)
for index, planet_data in enumerate(temp_speed_supporting_planets):
 if planet_speeds[index] > 200:
   speed_supporting_planets.remove(planet_data)


print(len(speed_supporting_planets))

habitable_planets = []
for planet in speed_supporting_planets:
  if planet in goldilock_planets:
    habitable_planets.append(planet)

print(len(habitable_planets))

final_dict = {}

for index, planet_data in enumerate(planet_data_rows):
  features_list = []
  gravity = (float(planet_data[3])*5.972e+24) / (float(planet_data[7])*float(planet_data[7])*6371000*6371000) * 6.674e-11
  try:
    if gravity < 100:
      features_list.append("gravity")
  except: pass
  try:
    if planet_data[6].lower() == "terrestrial" or planet_data[6].lower() == "super earth":
      features_list.append("planet_type")
  except: pass
  try:
    if planet_data[8] > 0.38 or planet_data[8] < 2:
      features_list.append("goldilock")
  except: pass
  try:
    distance = 2 * 3.14 * (planet_data[8] * 1.496e+8)
    time = planet_data[9] * 86400
    speed = distance / time
    if speed < 200:
      features_list.append("speed")
  except: pass
  final_dict[index] = features_list

print(final_dict)

gravity_planet_count = 0
for key, value in final_dict.items():
 if "gravity" in value:
   gravity_planet_count += 1


print(gravity_planet_count)

type_planet_count = 0
for key, value in final_dict.items():
 if "planet_type" in value:
   type_planet_count += 1


print(type_planet_count)

planet_not_gravity_support = []
for planet_data in planet_data_rows:
 if planet_data not in low_gravity_planets:
   planet_not_gravity_support.append(planet_data)


type_no_gravity_planet_count = 0
for planet_data in planet_not_gravity_support:
 if planet_data[6].lower() == "terrestrial" or planet_data[6].lower() == "super earth":
   type_no_gravity_planet_count += 1


print(type_no_gravity_planet_count)
print(type_planet_count - type_no_gravity_planet_count)

goldilock_planet_count = 0
for key, value in final_dict.items():
 if "goldilock" in value:
   goldilock_planet_count += 1


print(goldilock_planet_count)

speed_planet_count = 0
for key, value in final_dict.items():
 if "speed" in value:
   speed_planet_count += 1


print(speed_planet_count)

"""SA: This is same as above code for final_dct with some modifications to calculate distance and time. Run this and then again run the above code to calculate goldylock zone.

"""

final_dict = {}

for index, planet_data in enumerate(planet_data_rows):
  features_list = []
  gravity = (float(planet_data[3])*5.972e+24) / (float(planet_data[7])*float(planet_data[7])*6371000*6371000) * 6.674e-11
  try:
    if gravity < 100:
      features_list.append("gravity")
  except: pass
  try:
    if planet_data[6].lower() == "terrestrial" or planet_data[6].lower() == "super earth":
      features_list.append("planet_type")
  except: pass
  try:
    if float(planet_data[8].split(" ")[0]) > 0.38 and float(planet_data[8].split(" ")[0]) < 2:
     features_list.append("goldilock")
  except: pass
  try:
    distance = 2 * 3.14 * (float(planet_data[8].split(" ")[0]) * 1.496e+9)
    time, unit = planet_data[9].split(" ")[0], planet_data[9].split(" ")[1]
    if unit.lower() == "days":
      time = float(time)
    else:
      time = float(time) * 365
    time = time * 86400
    speed = distance / time
    if speed < 200:
      features_list.append("speed")
  except: pass
  final_dict[index] = features_list

print(final_dict)

goldilock_planet_count = 0
for key, value in final_dict.items():
 if "goldilock" in value:
   goldilock_planet_count += 1


print(goldilock_planet_count)

speed_planet_count = 0
for key, value in final_dict.items():
 if "speed" in value:
   speed_planet_count += 1


print(speed_planet_count)

goldilock_gravity_type_count = 0
for key, value in final_dict.items():
 if "goldilock" in value and "planet_type" in value and "gravity" in value:
   goldilock_gravity_type_count += 1


print(goldilock_gravity_type_count)

speed_goldilock_gravity_type_count = 0
for key, value in final_dict.items():
 if "goldilock" in value and "planet_type" in value and "gravity" in value and "speed" in value:
   speed_goldilock_gravity_type_count += 1


print(speed_goldilock_gravity_type_count)



"""Same sa above but removing the try and except from goldylock part of the code"""

final_dict = {}

for index, planet_data in enumerate(planet_data_rows):
  features_list = []
  gravity = (float(planet_data[3])*5.972e+24) / (float(planet_data[7])*float(planet_data[7])*6371000*6371000) * 6.674e-11
  try:
    if gravity < 100:
      features_list.append("gravity")
  except: pass
  try:
    if planet_data[6].lower() == "terrestrial" or planet_data[6].lower() == "super earth":
      features_list.append("planet_type")
  except: pass

  if float(planet_data[8].split(" ")[0]) > 0.38 and float(planet_data[8].split(" ")[0]) < 2:
    features_list.append("goldilock")

  try:
    distance = 2 * 3.14 * (float(planet_data[8].split(" ")[0]) * 1.496e+9)
    time, unit = planet_data[9].split(" ")[0], planet_data[9].split(" ")[1]
    if unit.lower() == "days":
      time = float(time)
    else:
      time = float(time) * 365
    time = time * 86400
    speed = distance / time
    if speed < 200:
      features_list.append("speed")
  except: pass
  final_dict[index] = features_list

print(final_dict)

"""Handel the exception orselves"""

final_dict = {}

for index, planet_data in enumerate(planet_data_rows):
  features_list = []
  gravity = (float(planet_data[3])*5.972e+24) / (float(planet_data[7])*float(planet_data[7])*6371000*6371000) * 6.674e-11
  try:
    if gravity < 100:
      features_list.append("gravity")
  except: pass
  try:
    if planet_data[6].lower() == "terrestrial" or planet_data[6].lower() == "super earth":
      features_list.append("planet_type")
  except: pass

  try:
    if float(planet_data[8].split(" ")[0]) > 0.38 and float(planet_data[8].split(" ")[0]) < 2:
      features_list.append("goldilock")
  except:
    try:
      if planet_data[8] > 0.38 and planet_data[8] < 2:
        features_list.append("goldilock")
    except:
        pass
  try:
    try:
      distance = 2 * 3.14 * (float(planet_data[8].split(" ")[0]) * 1.496e+9)
    except:
      try:
         distance = 2 * 3.14 * (float(planet_data[8]) * 1.496e+9)
      except: pass

    try:
      time, unit = planet_data[9].split(" ")[0], planet_data[9].split(" ")[1]
      if unit.lower() == "days":
        time = float(time)
      else:
        time = float(time) * 365
    except:
        time = planet_data[9]
    time = time * 86400
    speed = distance / time
    if speed < 200:
      features_list.append("speed")

  except: pass
  final_dict[index] = features_list


print(final_dict)

goldilock_gravity_type_count = 0
for key, value in final_dict.items():
 if "goldilock" in value and "planet_type" in value and "gravity" in value:
   goldilock_gravity_type_count += 1


print(goldilock_gravity_type_count)

speed_goldilock_gravity_type_count = 0
for key, value in final_dict.items():
 if "goldilock" in value and "planet_type" in value and "gravity" in value and "speed" in value:
   speed_goldilock_gravity_type_count += 1


print(speed_goldilock_gravity_type_count)